import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Header } from "@/components/navigation/Header";
import { Footer } from "@/components/navigation/Footer";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen dark:bg-background text-black dark:text-white font-sans antialiased",
          inter.variable
        )}
      >
        <Providers>
          <Header />
          <main className='max-w-[1250px] p-5 xl:px-0 mx-auto mt-[65px]'>
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
